### ISSUE TITLE
Remove the use of preemptive interfaces and export structs in your various packages

### ISSUE THREAD

**Issue by dprotaso** [tjarratt/go-best-practices#2]
Some perspective on this:
https://medium.com/@cep21/preemptive-interface-anti-pattern-in-go-54c18ac0668a
https://medium.com/@cep21/what-accept-interfaces-return-structs-means-in-go-2fe879e25ee8

**Comment by tjarratt** [comment]
I really enjoyed some of the conversations in Pivotal's Slack around this. Generally, the sentiment (as I remembered it) was that preemptively returning interfaces makes it a tad harder for consumers of packages to find the correct docs they are looking for. 

* returning an interface means I may need to look in two places 
* returning an interface means (important) decisions have already been made for me
* declaring client-side interfaces is easy (and valuable)

I agree with all of these things, but I think the part I could clarify about my intent is mostly about safety of types with Behavior.

Let's compare and contrast two packages, [domain](https://github.com/tjarratt/go-best-practices/tree/master/domain) and [api](https://github.com/tjarratt/go-best-practices/tree/master/api).

`domain` exports structs. Sure, there's an interface alongside too, if you want it, but it exports proper structs. These structs are just strongly typed dictionaries - objects with a certain shape, but no observable outside behavior, they're just data.

`api` exports interfaces. There are "constructors" for types like the `PizzaRepository`. Why is this?

Well, if you want to have a `PizzaRepository` that's backed by a real database, you probably need to give it some configuration, like a URL, username, password, maybe a database name. If it's just in-memory you probably want to configure it with a filesystem path. Why don't I export these structs here, while I gladly exported the structs in `domain`?

The difference is the degree of safety. You can easily call `Pepperoni{}` in your code, even if it took a `spicinessLevel` field as an int - defaulting to zero is fine here. However, if you called `new OracleBackedPizzaRepository{}` and forgot to pass it some credentials, that's just going to blow up at runtime. Forcing users to call a function, which is typed and checks the presence of non-optional fields catches a variety of runtime errors.

Is that a satisfactory answer @dprotaso? Do you agree that this pattern provides value here? More importantly, do you feel *heard*? My intent here is not to be a dictator, ignoring the unwashed masses' every word, ruling with an iron thumb, but rather to identify, clarify and share patterns that can benefit a wide variety of teams - from those very senior and well versed in Go, all the way down to very junior teams that will make a variety of mistakes along the way to Go Enlightenment.

Perhaps I've put a lot of emphasis on patterns for helping junior engineers. More so than the Go community at large may value.

**Comment by dprotaso** [comment]
> Forcing users to call a function, which is typed and checks the presence of non-optional fields catches a variety of runtime errors.

The stdlib does this https://golang.org/pkg/hash/

> Is that a satisfactory answer @dprotaso? Do you agree that this pattern provides value here? More importantly, do you feel heard?

Yes
